/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 124
#define YY_END_OF_BUFFER 125
static yyconst short int yy_acclist[538] =
    {   0,
      125,  123,  124,  124,   16,  123,  124,   38,  123,  124,
        5,  123,  124,  123,  124,    3,  123,  124,    1,  123,
      124,    2,  123,  124,  123,  124,    4,  123,  124,  119,
      122,  123,  124,  119,  122,  123,  124,   33,  123,  124,
       37,  123,  124,   21,  123,  124,    6,  123,  124,   22,
      123,  124,   34,  123,  124,   36,  123,  124,  118,  123,
      124,   25,  123,  124,   26,  123,  124,   39,  118,  123,
      124,  118,  123,  124,  118,  123,  124,  118,  123,  124,
      118,  123,  124,  118,  123,  124,  118,  123,  124,  118,
      123,  124,  118,  123,  124,  118,  123,  124,  118,  123,

      124,  118,  123,  124,  118,  123,  124,  118,  123,  124,
      118,  123,  124,  118,  123,  124,  118,  123,  124,  118,
      123,  124,  123,  124,   27,   18,   11,   14,    9,   12,
        7,   13,    8,   35,   31,  122,   10,  119,  122,  122,
       30,   23,   17,   24,   28,   29,  118,  118,  118,  118,
       40,  118,  118,   71,  118,  118,  118,  118,  118,  118,
      118,   45,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,   50,  118,  118,   51,  118,   54,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,   15,   20,

       52,   55,   32,  122,  120,  122,  121,   19,  118,  118,
      118,   41,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,   48,
      118,   49,  118,   79,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  108,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,   85,  118,
      118,  118,  118,  118,  118,  118,   64,  118,  118,   67,
      118,   68,  118,  118,  118,  120,  122,  121,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,   95,  118,
      118,  118,   46,  118,   96,  118,  118,  118,  118,  118,

       77,  118,  118,  118,  118,   81,  118,  118,  118,  118,
      118,  118,   56,  118,  118,  106,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,   61,  118,  118,   63,  118,  118,  118,
      118,   69,  118,  118,  118,  118,  118,  118,   42,  118,
       72,  118,   43,  118,  118,   93,  118,  118,  118,  118,
      118,  118,  118,   47,  118,   76,  118,   99,  118,  118,
      100,  118,  118,  102,  118,  118,  118,  118,  118,  118,
      118,  118,   82,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,   60,  118,  118,  118,   62,  118,  118,

      118,   87,  118,  118,   88,  118,   70,  118,  118,   90,
      118,  118,  118,  118,  118,  118,  118,  118,   97,  118,
      118,  118,   80,  118,  101,  118,  118,  118,  118,  118,
       57,  118,  118,  118,  118,  118,  118,  118,  112,  118,
      118,  118,   59,  118,  114,  118,  118,  118,  118,  118,
       66,  118,  117,  118,  118,  118,  118,  118,  118,  118,
      118,   75,  118,  118,   78,  118,  118,  118,  118,  118,
      118,  118,   58,  118,  110,  118,  118,  118,  118,  113,
      118,  118,  115,  118,  116,  118,  118,   89,  118,  118,
      118,  118,   44,  118,  118,   74,  118,   98,  118,  118,

      103,  118,  104,  118,  105,  118,  107,  118,  109,  118,
       83,  118,  118,   84,  118,   86,  118,  118,  118,   92,
      118,  118,  118,   53,  118,  111,  118,   65,  118,   91,
      118,  118,  118,   73,  118,   94,  118
    } ;

static yyconst short int yy_accept[396] =
    {   0,
        1,    1,    1,    2,    4,    5,    8,   11,   14,   16,
       19,   22,   25,   27,   30,   34,   38,   41,   44,   47,
       50,   53,   56,   59,   62,   65,   68,   72,   75,   78,
       81,   84,   87,   90,   93,   96,   99,  102,  105,  108,
      111,  114,  117,  120,  123,  125,  126,  127,  127,  128,
      129,  130,  131,  132,  133,  134,  135,  136,  137,  138,
      138,  140,  140,  140,  141,  141,  141,  142,  143,  144,
      145,  146,  147,  148,  149,  150,  151,  153,  154,  156,
      157,  158,  159,  160,  161,  162,  164,  165,  166,  167,
      168,  169,  170,  171,  172,  173,  175,  176,  178,  180,

      181,  182,  183,  184,  185,  186,  187,  188,  189,  190,
      191,  192,  193,  194,  195,  196,  197,  198,  199,  200,
      201,  202,  203,  204,  205,  205,  206,  206,  207,  208,
      209,  210,  211,  212,  213,  214,  215,  216,  217,  218,
      219,  220,  221,  222,  223,  224,  225,  226,  227,  228,
      229,  230,  232,  234,  236,  237,  238,  239,  240,  241,
      242,  243,  244,  245,  246,  247,  249,  250,  251,  252,
      253,  254,  255,  256,  257,  258,  259,  261,  262,  263,
      264,  265,  266,  267,  269,  270,  272,  274,  275,  276,
      277,  277,  278,  278,  279,  279,  280,  281,  282,  283,

      284,  285,  286,  287,  288,  289,  291,  292,  293,  295,
      297,  298,  299,  300,  301,  303,  304,  305,  306,  308,
      309,  310,  311,  312,  313,  315,  316,  318,  319,  320,
      321,  322,  323,  324,  325,  326,  327,  328,  329,  330,
      331,  332,  333,  334,  336,  337,  339,  340,  341,  342,
      344,  345,  346,  347,  348,  349,  351,  353,  355,  356,
      358,  359,  360,  361,  362,  363,  364,  366,  368,  370,
      371,  373,  374,  376,  377,  378,  379,  380,  381,  382,
      383,  385,  386,  387,  388,  389,  390,  391,  392,  393,
      394,  396,  397,  398,  400,  401,  402,  404,  405,  407,

      409,  410,  412,  413,  414,  415,  416,  417,  418,  419,
      421,  422,  423,  425,  427,  428,  429,  430,  431,  433,
      434,  435,  436,  437,  438,  439,  441,  442,  443,  445,
      447,  448,  449,  450,  451,  453,  455,  456,  457,  458,
      459,  460,  461,  462,  464,  465,  467,  468,  469,  470,
      471,  472,  473,  475,  477,  478,  479,  480,  482,  483,
      485,  487,  488,  490,  491,  492,  493,  495,  496,  498,
      500,  501,  503,  505,  507,  509,  511,  513,  514,  516,
      518,  519,  520,  522,  523,  524,  526,  528,  530,  532,
      533,  534,  536,  538,  538

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    1,    4,    5,    6,    1,    1,
        1,    7,    8,    1,    9,   10,   11,   12,   13,   14,
       14,   14,   14,   14,   14,   14,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   22,   22,   24,   25,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   27,   26,   26,
       28,    1,   29,    1,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   26,   47,   48,   49,   50,   51,   52,   53,
       54,   26,    1,   55,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[56] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    2,    2,    1,    1,    1,    1,    1,    1,
        1,    2,    2,    2,    2,    3,    3,    1,    1,    4,
        2,    2,    2,    2,    2,    2,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1
    } ;

static yyconst short int yy_base[398] =
    {   0,
        0,    0,  471,  472,  472,   53,  472,  452,  463,  450,
       49,   50,   48,  449,   83,   47,  451,  472,  447,  446,
      445,   62,  472,    0,  472,  472,    0,   32,   19,   44,
       67,   41,   72,  427,   80,  430,   37,   88,   83,  425,
       28,   94,  428,  420,  402,  472,  438,   40,  472,  472,
      472,  472,  472,  472,  472,  472,  438,  130,  472,  133,
        0,   92,  144,  472,    0,  137,  472,  472,  436,  472,
      472,  472,    0,  405,  403,  407,  430,  414,    0,  399,
      416,   83,  401,  396,  402,    0,  399,  394,  391,   91,
      398,  126,  392,  394,  388,    0,  390,  133,    0,  386,

      395,  391,  392,  396,  381,  394,  126,   90,  396,  141,
       50,  116,  388,   62,  113,  380,  129,  144,  472,  472,
      472,  472,  472,  172,  175,  179,  181,  186,  395,  472,
      375,  373,  377,  472,  390,  387,  371,  372,  155,  369,
      385,  380,  383,  378,  369,  376,  375,  361,  366,  372,
      375,    0,    0,    0,  360,  365,  354,  363,  366,  365,
      364,  354,  355,  361,  134,    0,  348,  353,  362,  341,
      164,  349,  355,  353,  338,  345,  340,  350,  338,  341,
      334,  336,  345,    0,  344,  328,  346,  168,  334,  193,
      205,  207,  212,  345,  344,  326,  341,  322,  329,  331,

      320,  336,  317,  326,  316,    0,  326,  319,    0,    0,
      328,  313,  324,  324,    0,  315,  309,  302,    0,  310,
      306,  305,  312,  308,    0,  316,    0,  317,  300,  315,
      302,  313,  308,  307,  302,  301,  300,  291,  302,  305,
      288,  299,  286,    0,  280,    0,  183,  296,  283,    0,
      294,  293,  296,  284,  294,    0,    0,    0,  280,  276,
      278,  282,  289,  280,  269,  273,    0,    0,  274,  266,
        0,  279,    0,  191,  269,  273,  262,  261,  270,  271,
        0,  258,  259,  272,  271,  252,  267,  257,  266,  252,
        0,  254,  262,    0,  254,  259,    0,  257,    0,    0,

      260,    0,  243,  252,  240,  239,  244,  238,  253,    0,
      254,  230,    0,    0,  252,  251,  242,  236,    0,  234,
      244,  242,  241,  226,  225,    0,  238,  238,    0,    0,
      240,  236,  236,  229,    0,    0,  218,  227,  220,  231,
      228,  220,  226,    0,  218,    0,  226,  216,  208,  221,
      208,  219,    0,    0,  199,  217,  204,    0,  207,    0,
        0,  217,    0,  196,  196,  190,    0,  199,    0,    0,
      201,    0,    0,    0,    0,    0,    0,  200,    0,    0,
      185,  187,    0,  185,  185,    0,    0,    0,    0,  154,
       96,    0,    0,  472,  242,   88,  245

    } ;

static yyconst short int yy_def[398] =
    {   0,
      394,    1,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,   15,  394,  394,  394,  394,
      394,  394,  394,  395,  394,  394,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
       16,  394,  394,  394,  396,  394,  394,  394,  394,  394,
      394,  394,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,

      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  397,  394,
      395,  395,  395,  394,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  394,
      394,  394,  394,  397,  397,  395,  395,  395,  395,  395,

      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,

      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,    0,  394,  394,  394

    } ;

static yyconst short int yy_nxt[528] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   24,   24,   24,   24,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   24,   35,   24,
       24,   36,   24,   37,   38,   39,   40,   41,   42,   24,
       43,   44,   24,   24,   45,   46,   52,   57,   54,   58,
       58,   58,  111,   74,   75,   78,   53,   55,   56,  394,
       47,   71,   79,  394,   80,   76,   72,  112,  394,   77,
      176,  101,   88,  121,   89,   81,  102,  122,   82,  129,
       83,   48,   60,   90,   61,   61,   61,   84,  177,  394,

      181,   85,   91,  126,  126,   62,   63,   64,  182,   65,
       92,   86,   66,  107,   62,   96,   93,   63,   64,  103,
       87,   94,   97,   98,  113,  138,  139,   99,  170,  108,
      393,  114,  109,  104,  171,   65,  146,  105,  106,  147,
      115,  124,  124,  124,   58,   58,   58,  116,   61,   61,
       61,  127,  127,   63,   64,  128,  128,  128,  168,  125,
      149,  178,  183,  179,   63,   64,  184,  150,  156,  151,
      186,  157,  169,  173,  158,  187,  159,  227,  188,  174,
      228,  160,  189,  124,  124,  124,  124,  124,  124,  175,
      190,  190,  128,  128,  128,   63,   64,  192,  192,  192,

      392,  125,  203,  204,  190,  190,   63,   64,  191,  233,
       64,  250,  234,  295,  251,  193,  190,  190,  192,  192,
      192,   64,  191,  192,  192,  192,  315,  296,  391,  390,
      389,   64,  388,  387,  316,  386,  193,  385,  384,  383,
      382,  193,   64,   73,   73,   73,  194,  381,  194,  380,
      379,  378,  377,  376,  375,  374,  373,  372,  371,  370,
      369,  368,  367,  366,  365,  364,  363,  362,  361,  360,
      359,  358,  357,  356,  355,  354,  353,  352,  351,  350,
      349,  348,  347,  346,  345,  344,  343,  342,  341,  340,
      339,  338,  337,  336,  335,  334,  333,  332,  331,  330,

      329,  328,  327,  326,  325,  324,  323,  322,  321,  320,
      319,  318,  317,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  294,  293,  292,  291,  290,  289,  288,  287,  286,
      285,  284,  283,  282,  281,  280,  279,  278,  277,  276,
      275,  274,  273,  272,  271,  270,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  259,  258,  257,  256,
      255,  254,  253,  394,  195,  252,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  232,  231,  230,  229,  226,  225,  224,  223,  222,

      221,  220,  219,  218,  217,  216,  215,  214,  213,  212,
      211,  210,  209,  208,  207,  206,  205,  202,  201,  200,
      199,  198,  197,  196,  195,  185,  180,  172,  167,  166,
      165,  164,  163,  162,  161,  155,  154,  153,  152,  148,
      145,  144,  143,  142,  141,  140,  137,  136,  135,  134,
      133,  132,  131,  130,  123,  120,  119,  118,  117,  110,
      100,   95,   70,   69,   68,   67,   59,   51,   50,   49,
      394,    3,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,

      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394
    } ;

static yyconst short int yy_chk[528] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    6,   11,   13,   12,   13,
       13,   13,   41,   28,   28,   29,   11,   12,   12,   16,
        6,   22,   29,   16,   30,   28,   22,   41,   16,   28,
      111,   37,   32,   48,   32,   30,   37,   48,   30,  396,
       30,    6,   15,   32,   15,   15,   15,   31,  111,   16,

      114,   31,   33,   62,   62,   15,   15,   15,  114,   15,
       33,   31,   15,   39,   15,   35,   33,   15,   15,   38,
       31,   33,   35,   35,   42,   82,   82,   35,  108,   39,
      391,   42,   39,   38,  108,   15,   90,   38,   38,   90,
       42,   58,   58,   58,   60,   60,   60,   42,   66,   66,
       66,   63,   63,   58,   58,   63,   63,   63,  107,   58,
       92,  112,  115,  112,   58,   58,  115,   92,   98,   92,
      117,   98,  107,  110,   98,  117,   98,  165,  118,  110,
      165,   98,  118,  124,  124,  124,  125,  125,  125,  110,
      126,  126,  127,  127,  127,  124,  124,  128,  128,  128,

      390,  124,  139,  139,  190,  190,  124,  124,  126,  171,
      128,  188,  171,  247,  188,  128,  191,  191,  192,  192,
      192,  128,  190,  193,  193,  193,  274,  247,  385,  384,
      382,  192,  381,  378,  274,  371,  192,  368,  366,  365,
      364,  193,  192,  395,  395,  395,  397,  362,  397,  359,
      357,  356,  355,  352,  351,  350,  349,  348,  347,  345,
      343,  342,  341,  340,  339,  338,  337,  334,  333,  332,
      331,  328,  327,  325,  324,  323,  322,  321,  320,  318,
      317,  316,  315,  312,  311,  309,  308,  307,  306,  305,
      304,  303,  301,  298,  296,  295,  293,  292,  290,  289,

      288,  287,  286,  285,  284,  283,  282,  280,  279,  278,
      277,  276,  275,  272,  270,  269,  266,  265,  264,  263,
      262,  261,  260,  259,  255,  254,  253,  252,  251,  249,
      248,  245,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  226,  224,
      223,  222,  221,  220,  218,  217,  216,  214,  213,  212,
      211,  208,  207,  205,  204,  203,  202,  201,  200,  199,
      198,  197,  196,  195,  194,  189,  187,  186,  185,  183,
      182,  181,  180,  179,  178,  177,  176,  175,  174,  173,
      172,  170,  169,  168,  167,  164,  163,  162,  161,  160,

      159,  158,  157,  156,  155,  151,  150,  149,  148,  147,
      146,  145,  144,  143,  142,  141,  140,  138,  137,  136,
      135,  133,  132,  131,  129,  116,  113,  109,  106,  105,
      104,  103,  102,  101,  100,   97,   95,   94,   93,   91,
       89,   88,   87,   85,   84,   83,   81,   80,   78,   77,
       76,   75,   74,   69,   57,   47,   45,   44,   43,   40,
       36,   34,   21,   20,   19,   17,   14,   10,    9,    8,
        3,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,

      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#define YY_NEVER_INTERACTIVE 1
#line 6 "lexer.l"
#include <stdio.h>
#include <string.h>
#include <limits.h>

#define PRINT_ERROR() printf("Found error in line: %d\n", yytext)
#define PRINT_OPERATOR() printf("Found operator: %s\n", yytext)
#define PRINT_HARD_KEYWORD() printf("Found hard keyword: %s\n", yytext)
#define PRINT_SOFT_KEYWORD() printf("Found soft keyword: %s\n", yytext)
#define PRINT_MODIFIER_KEYWORD() printf("Found modifier keyword: %s\n", yytext)
#define PRINT_IDENTIFIER() printf("Found identifier: %s\n", yytext)
#define PRINT_DECIMAL_INTEGER() printf("Found decimal integer: %d\n", _integerNumber)
#define PRINT_BINARY_INTEGER() printf("Found binary integer: %d\n", _integerNumber)
#define PRINT_HEXADECIMAL_INTEGER() printf("Found hexadecimal integer: %d\n", _integerNumber)
#define PRINT_FLOATING_POINT_NUMBER() printf("Found double number: %f\n", _doubleNumber)

#line 701 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 23 "lexer.l"



    void removeUnderscores(char* str) {
        int src = 0;
        int dst = 0;
        while (str[src] != '\0')
        {
            if (str[src] != '_')
            {
                str[dst] = str[src];
                ++dst;
            }
            ++src;
        }
        str[dst] = '\0';
    }



    char _string[SHRT_MAX];
    long long _integerNumber;
    double _doubleNumber;


#line 878 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 395 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 472 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 48 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 49 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 50 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 51 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 52 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 53 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 54 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 55 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 56 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 57 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 58 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 59 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 60 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 61 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 62 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 63 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 64 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 65 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 66 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 67 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 68 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 69 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 70 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 71 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 72 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 73 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 74 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 75 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 76 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 77 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 78 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 79 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 80 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 81 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 82 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 83 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 84 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 85 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 86 "lexer.l"
{ PRINT_OPERATOR(); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 89 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 90 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 91 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 92 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 93 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 94 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 95 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 96 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 97 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 98 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 99 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 100 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 101 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 102 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 103 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 104 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 105 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 106 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 107 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 108 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 109 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 110 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 111 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 112 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 113 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 114 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 115 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 116 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 117 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 118 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 119 "lexer.l"
{ PRINT_HARD_KEYWORD(); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 122 "lexer.l"
{ PRINT_SOFT_KEYWORD(); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 123 "lexer.l"
{ PRINT_SOFT_KEYWORD(); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 124 "lexer.l"
{ PRINT_SOFT_KEYWORD(); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 125 "lexer.l"
{ PRINT_SOFT_KEYWORD(); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 126 "lexer.l"
{ PRINT_SOFT_KEYWORD(); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 127 "lexer.l"
{ PRINT_SOFT_KEYWORD(); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 128 "lexer.l"
{ PRINT_SOFT_KEYWORD(); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 129 "lexer.l"
{ PRINT_SOFT_KEYWORD(); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 130 "lexer.l"
{ PRINT_SOFT_KEYWORD(); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 131 "lexer.l"
{ PRINT_SOFT_KEYWORD(); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 132 "lexer.l"
{ PRINT_SOFT_KEYWORD(); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 133 "lexer.l"
{ PRINT_SOFT_KEYWORD(); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 134 "lexer.l"
{ PRINT_SOFT_KEYWORD(); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 135 "lexer.l"
{ PRINT_SOFT_KEYWORD(); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 136 "lexer.l"
{ PRINT_SOFT_KEYWORD(); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 137 "lexer.l"
{ PRINT_SOFT_KEYWORD(); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 138 "lexer.l"
{ PRINT_SOFT_KEYWORD(); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 139 "lexer.l"
{ PRINT_SOFT_KEYWORD(); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 142 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 143 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 144 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 145 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 146 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 147 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 148 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 149 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 150 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 151 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 152 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 153 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 154 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 155 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 156 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 157 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 158 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 159 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 160 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 161 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 162 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 163 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 164 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 165 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 166 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 167 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 168 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 169 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 170 "lexer.l"
{ PRINT_MODIFIER_KEYWORD(); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 172 "lexer.l"
{ PRINT_IDENTIFIER(); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 174 "lexer.l"
{ _string[0] = 0;
    strcat(_string, yytext);
    if (_string[0] == '0' && strlen(_string) > 1)
    {
        PRINT_ERROR();
        printf("Leading zero in integer type");
    }
    else
    {
        removeUnderscores(_string);
        _integerNumber = strtoll(_string, NULL, 1);
        PRINT_DECIMAL_INTEGER();
    }
}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 189 "lexer.l"
{ _string[0] = 0;
    strcat(_string, yytext);
    removeUnderscores(_string);
    int _integerNumber = strtoll(_string + 2, NULL, 2);
    PRINT_BINARY_INTEGER();
}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 196 "lexer.l"
{
    _string[0] = 0;
    strcat(_string, yytext);
    removeUnderscores(_string);
    _integerNumber = strtoll(_string + 2, NULL, 16);
    PRINT_HEXADECIMAL_INTEGER();
}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 204 "lexer.l"
{
    _string[0] = 0;
    strcat(_string, yytext);
    removeUnderscores(_string);
    _doubleNumber = atof(_string);
    PRINT_FLOATING_POINT_NUMBER();
}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 212 "lexer.l"
{}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 213 "lexer.l"
ECHO;
	YY_BREAK
#line 1619 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 395 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 395 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 394);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 213 "lexer.l"


int main(int argc, char **argv) {
    yylex();
    return 0;
}